server:
  port: 8888
spring:
  application:
    name: config-center-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mammclj/spring-cloud-config-test.git
          search-paths: respo
          default-label: master
          username:
          password: